Do not export hidden objects
Kupoman/blendergltf pull request #28
Opened 2016-10-09 12:01 UTC by onox

2016-10-09 12:10 UTC, onox commented
I can modify the PR to fix #17 if you want.

2016-10-09 17:27 UTC, Moguri commented
There are use cases where you may want to export hidden nodes, so this should be controlled by a setting.

2016-10-10 07:00 UTC, onox commented
I'll add a checkbox "Export Hidden Objects". Does that sound OK?

2016-10-15 23:14 UTC, Kupoman requested changes
I'm a little concerned about the performance of your implementation, but we can address that later if it becomes a problem. For now, I think just fixing the settings issue should be enough to get this into master.

2016-10-15 23:14 UTC, Kupoman commented on __init__.py
> +        nodes_selected_only = BoolProperty(name='Selection Only', default=False)
These settings also need to be added to the default_settings dictionary near the top of blendergltf.py.

2016-10-16 17:52 UTC, Kupoman approved these changes

2016-10-16 17:53 UTC, merged